import http from 'node:http'; import fs from 'node:fs/promises'; import path from 'node:path'; import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'; import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js'; import { z } from 'zod'; import { BrowserManager } from '../browser/manager.js'; import { landedCost, grossProfit, grossMargin } from '../scoring/margin.js';
const stores={motoryn:{slug:'motoryn',autodsStoreId:5669701,shopifyDomain:'narnxh-zu.myshopify.com'},shoponifinda:{slug:'shoponifinda',autodsStoreId:5669573,shopifyDomain:'autods-user-store-34097-axxec1ix.myshopify.com'}} as const; const ss=z.enum(['motoryn','shoponifinda']); type Store=keyof typeof stores; const data=async(s:Store)=>{try{return JSON.parse(await fs.readFile(path.resolve('var/reports',`${s}-products.json`),'utf8'))}catch{return[]}}; const clean=(x:any)=>{const {raw,...y}=x;return y}; const out=(x:any,t:string)=>({structuredContent:x as Record<string,unknown>,content:[{type:'text' as const,text:t}]});
export function createMcpServer(){const s=new McpServer({name:'shopify-autods-bridge',version:'1.0.0'},{instructions:'Read-only commerce and social bridge. Require an explicit store or brand. No deletion, publishing, or browser-control tools are enabled.'}); const ro={readOnlyHint:true,destructiveHint:false,openWorldHint:false} as const;
 s.registerTool('list_stores',{title:'List connected stores',description:'List verified AutoDS and Shopify stores.',inputSchema:{},annotations:ro},async()=>out({stores:Object.values(stores)},'Two verified stores are configured.'));
 s.registerTool('get_store_products',{title:'Get store products',description:'Read products for one explicit store.',inputSchema:{store:ss,limit:z.number().int().min(1).max(100).default(50),offset:z.number().int().min(0).default(0)},annotations:ro},async({store,limit,offset})=>{const a=await data(store);return out({store,storeId:stores[store].autodsStoreId,total:a.length,products:a.slice(offset,offset+limit).map(clean)},`Returned ${Math.min(limit,a.length-offset)} products.`)});
 s.registerTool('get_product',{title:'Get product',description:'Read one normalized product by ID.',inputSchema:{store:ss,product_id:z.string()},annotations:ro},async({store,product_id})=>{const p=(await data(store)).find((x:any)=>String(x.autodsId??x.id)===product_id);return out({store,product:p?clean(p):null},p?'Product returned.':'Product not found.')});
 s.registerTool('search_autods',{title:'Search AutoDS',description:'Search existing normalized inventory and report catalog-search availability.',inputSchema:{store:ss,query:z.string().min(2),limit:z.number().int().min(1).max(50).default(20)},annotations:{...ro,openWorldHint:true}},async({store,query,limit})=>{const q=query.toLowerCase();const m=(await data(store)).filter((x:any)=>String(x.originalTitle??x.title).toLowerCase().includes(q)).slice(0,limit).map(clean);return out({store,query,matches:m,catalogSearchStatus:'not_available_in_current_session'},`Found ${m.length} existing matches; catalog status is explicitly unavailable.`)});
 s.registerTool('search_automotive_products',{title:'Search automotive products',description:'Find MOTORYN products by automotive category.',inputSchema:{category:z.enum(['vacuum','inflator','carplay','jump_starter','obd','dash_cam','tpms','hud','detailing','road_trip','unique_tech']),limit:z.number().int().min(1).max(50).default(20)},annotations:{...ro,openWorldHint:true}},async({category,limit})=>{const terms:any={vacuum:['vacuum','blower'],inflator:['inflator','compressor'],carplay:['carplay','android auto'],jump_starter:['jump starter'],obd:['obd','diagnostic'],dash_cam:['dash cam','rearview'],tpms:['tpms'],hud:['hud','gps'],detailing:['detail','brush','towel','wiper'],road_trip:['road','mattress','organizer'],unique_tech:['smart','wireless','digital','electric']};const m=(await data('motoryn')).filter((x:any)=>terms[category].some((t:string)=>String(x.originalTitle??x.title).toLowerCase().includes(t))).slice(0,limit).map(clean);return out({store:'motoryn',category,candidates:m,catalogSearchStatus:'not_available_in_current_session'},`Returned ${m.length} MOTORYN matches.`)});
 s.registerTool('calculate_product_economics',{title:'Calculate economics',description:'Calculate landed cost, gross profit, and gross margin.',inputSchema:{source_cost:z.number().nonnegative(),shipping:z.number().nonnegative(),retail_price:z.number().positive()},annotations:ro},async({source_cost,shipping,retail_price})=>{const l=landedCost(source_cost,shipping)!;return out({landed_cost:l,gross_profit:grossProfit(retail_price,l),gross_margin:grossMargin(retail_price,l)},'Economics calculated.')});
 s.registerTool('rank_candidates',{title:'Rank candidates',description:'Rank existing normalized products for merchandising.',inputSchema:{store:ss,target_margin:z.number().min(0).max(1).default(.6),query:z.string().optional()},annotations:ro},async({store,query,target_margin})=>{const q=query?.toLowerCase();const a=(await data(store)).filter((x:any)=>!q||String(x.originalTitle??x.title).toLowerCase().includes(q)).map((x:any)=>({product:clean(x),targetMargin:target_margin,decision:x.decision??'REVIEW'}));return out({store,candidates:a},`Ranked ${a.length} products.`)});
 s.registerTool('get_product_audit',{title:'Get product audit',description:'Read the current product audit.',inputSchema:{store:ss},annotations:ro},async({store})=>out({store,products:(await data(store)).map(clean)},'Audit returned.'));
 s.registerTool('get_store_strategy',{title:'Get store strategy',description:'Read current merchandising strategy and evidence gaps.',inputSchema:{store:ss},annotations:ro},async({store})=>{try{return out({store,summary:await fs.readFile(path.resolve('var/reports',`${store}-product-strategy.md`),'utf8')},'Strategy returned.')}catch{return out({store,summary:null},'No strategy report available.')}});
 s.registerTool('health',{title:'Bridge health',description:'Read MCP, Edge/CDP, AutoDS and report health.',inputSchema:{},annotations:ro},async()=>{const b=new BrowserManager();let st:any={cdp_reachable:false,edge_reachable:false,autods_authenticated:false};try{await b.attach();st=b.status()}catch{}return out({mcp:'ok',...st,stores:Object.fromEntries(await Promise.all(Object.keys(stores).map(async k=>[k,(await data(k as Store)).length])))},'Health returned.')});
 s.registerTool('search',{title:'Search bridge data',description:'Standard discovery search across store products.',inputSchema:{query:z.string().min(1),store:ss.optional()},annotations:ro},async({query,store})=>{const q=query.toLowerCase();const sl:Store[]=store?[store]:['motoryn','shoponifinda'];const r=(await Promise.all(sl.map(async k=>(await data(k)).filter((x:any)=>JSON.stringify(x).toLowerCase().includes(q)).map((x:any)=>({id:String(x.autodsId??x.id),title:x.originalTitle??x.title,store:k}))))).flat();return out({results:r},`Found ${r.length} results.`)});
 s.registerTool('fetch',{title:'Fetch bridge result',description:'Fetch one product result by ID and store.',inputSchema:{id:z.string(),store:ss},annotations:ro},async({id,store})=>{const p=(await data(store)).find((x:any)=>String(x.autodsId??x.id)===id);return out({id,store,data:p?clean(p):null},p?'Fetched.':'Not found.')}); return s;}
export async function startMcpServer(){const port=Number(process.env.MCP_PORT??8788),secret=process.env.MCP_SHARED_SECRET,required=process.env.MCP_REQUIRE_AUTH==='true',sessions=new Map<string,StreamableHTTPServerTransport>();const h=http.createServer(async(req,res)=>{if(req.url!=='/mcp'){res.writeHead(404);return res.end('Not found')}if(required&&(!secret||req.headers.authorization!==`Bearer ${secret}`)){res.writeHead(401,{'WWW-Authenticate':'Bearer'});return res.end('Unauthorized')}let body='';req.on('data',c=>body+=c);req.on('end',async()=>{try{const sid=String(req.headers['mcp-session-id']??'');let t=sid?sessions.get(sid):undefined;if(!t){const s=createMcpServer();t=new StreamableHTTPServerTransport({sessionIdGenerator:()=>crypto.randomUUID(),onsessioninitialized:(id)=>{sessions.set(id,t!)}});await s.connect(t)}await t.handleRequest(req,res,body?JSON.parse(body):undefined)}catch{if(!res.headersSent){res.writeHead(500);res.end('MCP request failed')}}})});await new Promise<void>(r=>h.listen(port,'127.0.0.1',r));console.log(JSON.stringify({mcp:'listening',host:'127.0.0.1',port,authRequired:required}));}
